### PR TITLE
Updated readme, because of some start problems, howto setup system.

### PR DESCRIPTION
**Pull request by jolo1581**
Just had some start issues, howto setup my system to build an example.
Also corrected makefile for starting with the led example without
building errors.

### CODE REVIEW

**Comment by nickray** [comment]
I think it would be better to link to the Rust Embedded book for setup instructions (https://rust-embedded.github.io/book/intro/install.html).

The actual firmware repository (to be published "soon") will have its own "book" where we can add more specific details.

**Comment by jolo1581** [comment]
Thanks for feedback.
I will replace my changes with the lunk above and do a forced push

**Comment by jolo1581** [comment]
I reworked my commit and did a forced push

**Comment by nickray** [comment]
Thanks!

As a general remark (not of relevance here), Rust ecosystem prefers kebab-case over snake_case wherever syntactically allowed.

**Pull request merged**
